package com.chefkoochooloo.dao

import groovy.transform.ToString

@ToString(includePackage=false, includeNames=true, excludes="")
class Country {

  Integer id
  Integer ent
  Integer opt
  Integer population
  String capital
  String code
  String cover_url
  String flag_url
  String languages
  String name
  String wish

  static mapping = {
    table '`country`'
    cache true
    version false
  }

  static constraints = {
    ent blank: true
    opt blank: true
  }
}


/*
CREATE TABLE ZCOUNTRY (
Z_PK INTEGER PRIMARY KEY,
Z_ENT INTEGER,
Z_OPT INTEGER,
ZPOPULATION INTEGER,
ZCAPITAL VARCHAR,
ZCODE VARCHAR,
ZCOVER VARCHAR,
ZFLAG VARCHAR,
ZLANGUAGES VARCHAR,
ZNAME VARCHAR,
ZWISH VARCHAR
);


CREATE TABLE ZCOUNTRY ( Z_PK INTEGER PRIMARY KEY, Z_ENT INTEGER, Z_OPT INTEGER, ZPOPULATION INTEGER, ZCAPITAL VARCHAR, ZCODE VARCHAR, ZCOVER VARCHAR, ZFLAG VARCHAR, ZLANGUAGES VARCHAR, ZNAME VARCHAR, ZWISH VARCHAR );
CREATE TABLE ZCOUNTRYCHARITY ( Z_PK INTEGER PRIMARY KEY, Z_ENT INTEGER, Z_OPT INTEGER, ZCOUNTRY INTEGER, ZDONATE VARCHAR, ZURL VARCHAR );
CREATE INDEX ZCOUNTRYCHARITY_ZCOUNTRY_INDEX ON ZCOUNTRYCHARITY (ZCOUNTRY);
CREATE TABLE ZCOUNTRYFACT ( Z_PK INTEGER PRIMARY KEY, Z_ENT INTEGER, Z_OPT INTEGER, ZCOUNTRY INTEGER, ZFACT VARCHAR );
CREATE INDEX ZCOUNTRYFACT_ZCOUNTRY_INDEX ON ZCOUNTRYFACT (ZCOUNTRY);
CREATE TABLE ZCOUNTRYLANGUAGE ( Z_PK INTEGER PRIMARY KEY, Z_ENT INTEGER, Z_OPT INTEGER, ZCOUNTRY INTEGER, ZLANGUAGE INTEGER );
CREATE INDEX ZCOUNTRYLANGUAGE_ZCOUNTRY_INDEX ON ZCOUNTRYLANGUAGE (ZCOUNTRY);
CREATE INDEX ZCOUNTRYLANGUAGE_ZLANGUAGE_INDEX ON ZCOUNTRYLANGUAGE (ZLANGUAGE);

 */